### ISSUE TITLE
reduce and missing colon 

### ISSUE THREAD

**Issue by KipCrossing** [inmcm/MTK_commands#2]
Hey, me again.

I just spotted a few thing in mtk.py. Firstly, it seams that micro python does not come with the reduce function by default and I had to add it in. Secondly, it seems like you have missed a colon at the end of line 183:

```
    if new_char in string.printable        #<- here
```

Other than that, all the commands are working however, I am finding it hard to receive a response, as per your examples in the README file, and it is perpetually stuck in the loop. Have I missed something?

Thanks, Kip

**Comment by inmcm** [comment]
I reverted the code back to a version that is more compatible with Micropython. Give the newest version of master a try.
